[workspace]
resolver = "2"
members = [
    "packages/content_core",
    "packages/ui",
    "packages/web",
    "packages/api",
]

[workspace.dependencies]
dioxus = { version = "0.7.1" }

# workspace
content_core = { path = "packages/content_core" }
ui = { path = "packages/ui" }
api = { path = "packages/api" }
